spring:
  application:
    name: spring-my-web
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springweb
    username: root
    password: my123456sql
  #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #跨域请求配置
#  mvc:
#    cors:
#      mapping: /**
#      allowed-origins: http://localhost:7000/
#      allowed-methods: GET, POST, PUT, DELETE
#      allowed-headers: "*"
#      allowed-credentials: true

#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#自定义阿里云配置
aliyun:
  oss:
    endpoint: http://apr-akina.online
    bucketname: akina

#开启事务管理日志
logging:
  level:
    org.springframework.jdbc.support.jdbcTransactionManager: debug

