spring:
  application:
    name: spring-my-web
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springweb
    username: root
    password: my123456sql
  #文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#自定义阿里云配置
aliyun:
  oss:
    endpoint: https://oss-cn-wuhan-lr.aliyuncs.com
    bucketname: hspacetest


